// d-league web/staticData.ts

import { Team } from './types';

// ==========================================
//   球隊資料 (TEAMS)
// ==========================================
export const TEAMS: Record<string, Team> = {
  // L1 Teams (4 teams)
  't_chiayi': { id: 't_chiayi', name: '嘉義諸羅山FC', shortName: '嘉義諸羅山FC', logo: '/d-league/assets/teams/chiayi.png', primaryColor: '#90d1d2', secondaryColor: '#0e3679' },
  't_jiuhao': { id: 't_jiuhao', name: '酒號矯正署', shortName: '酒號矯正署', logo: '/d-league/assets/teams/jiuhao.png', primaryColor: '#000000', secondaryColor: '#ffffff' },
  't_tongque': { id: 't_tongque', name: '銅雀足球俱樂部', shortName: '銅雀足球俱樂部',logo: '/d-league/assets/teams/tongque.png', primaryColor: '#2a2b30', secondaryColor: '#ffffff' },
  't_chen': { id: 't_chen', name: '陳公舘', shortName: '陳公舘', logo: '/d-league/assets/teams/chen.png', primaryColor: '#000000', secondaryColor: '#8ac4e1' },
  
  // L2 Teams (6 teams)
  't_luzhu': { id: 't_luzhu', name: '鹿逐俱樂部', shortName: '鹿逐俱樂部', logo: '/d-league/assets/teams/luzhu.png', primaryColor: '#385984', secondaryColor: '#ffffff' },
  't_pingtung': { id: 't_pingtung', name: '屏東野猿足球俱樂部', shortName: '屏東野猿足球俱樂部', logo: '/d-league/assets/teams/pingtung.png', primaryColor: '#563e92', secondaryColor: '#ffffff' },
  't_crazydog': { id: 't_crazydog', name: '瘋Dog', shortName: '瘋Dog', logo: '/d-league/assets/teams/crazydog.png', primaryColor: '#ed8992', secondaryColor: '#000000' },
  't_canglong': { id: 't_canglong', name: '蒼龍FC', shortName: '蒼龍FC', logo: '/d-league/assets/teams/canglong.png', primaryColor: '#0c2450', secondaryColor: '#ffffff' },
  't_ppi': { id: 't_ppi', name: 'PPI TAINAN', shortName: 'PPI TAINAN', logo: '/d-league/assets/teams/ppi.png', primaryColor: '#004026', secondaryColor: '#ffffff' },
  // ✅ 修改：鳥仕主色改為 #be1920
  't_niaoshi': { id: 't_niaoshi', name: '鳥仕足球俱樂部', shortName: '鳥仕足球俱樂部', logo: '/d-league/assets/teams/niaoshi.png', primaryColor: '#be1920' },
};

// ==========================================
//   球員照片路徑 (PLAYER_IMAGES)
// ==========================================
export const PLAYER_IMAGES: Record<string, string> = {
  // L1 - 嘉義諸羅山FC
  '陳日揚': '/d-league/assets/players/嘉義諸羅山FC/陳日揚.png',
  '陳官澤': '/d-league/assets/players/嘉義諸羅山FC/陳官澤.png',
  '陳柏翰': '/d-league/assets/players/嘉義諸羅山FC/陳柏翰.png',
  '蔡孟勲': '/d-league/assets/players/嘉義諸羅山FC/蔡孟勲.png',
  'Jason Chan': '/d-league/assets/players/嘉義諸羅山FC/Jason Chan.png',
  '黃子睿': '/d-league/assets/players/嘉義諸羅山FC/黃子睿.png',
  '黃偉倫': '/d-league/assets/players/嘉義諸羅山FC/黃偉倫.png',
  '王至皓': '/d-league/assets/players/嘉義諸羅山FC/王至皓.png',
  '唐毓翔': '/d-league/assets/players/嘉義諸羅山FC/唐毓翔.png',
  '林柏辰': '/d-league/assets/players/嘉義諸羅山FC/林柏辰.png',
  '李裕玄': '/d-league/assets/players/嘉義諸羅山FC/李裕玄.png',
  '鄭州偉': '/d-league/assets/players/嘉義諸羅山FC/鄭州偉.png',
  '蔡吉雄': '/d-league/assets/players/嘉義諸羅山FC/蔡吉雄.png',
  '郭政達': '/d-league/assets/players/嘉義諸羅山FC/郭政達.png',
  '王建翔': '/d-league/assets/players/嘉義諸羅山FC/王建翔.png',
  '黃楷堯': '/d-league/assets/players/嘉義諸羅山FC/黃楷堯.png',
  '李俊逵': '/d-league/assets/players/嘉義諸羅山FC/李俊逵.png',
  // ✅ 新增
  '溫立丞': '/d-league/assets/players/嘉義諸羅山FC/溫立丞.png',
  '李坤城': '/d-league/assets/players/嘉義諸羅山FC/李坤城.png',
  '李鎮宇': '/d-league/assets/players/嘉義諸羅山FC/李鎮宇.png',
  
  // L1 - 陳公舘
  '李秉錦': '/d-league/assets/players/陳公舘/李秉錦.png',
  '林家銘': '/d-league/assets/players/陳公舘/林家銘.png',
  '倪柏瑄': '/d-league/assets/players/陳公舘/倪柏瑄.png',
  '孫裕程': '/d-league/assets/players/陳公舘/孫裕程.png',
  '洪品丞': '/d-league/assets/players/陳公舘/洪品丞.png',
  '陳立鑫': '/d-league/assets/players/陳公舘/陳立鑫.png',
  '潘志豪': '/d-league/assets/players/陳公舘/潘志豪.png',
  '倪天銘': '/d-league/assets/players/陳公舘/倪天銘.png',
  '楊俊雄': '/d-league/assets/players/陳公舘/楊俊雄.png',
  // ❌ 已移除：劉振仕 (轉出)
  '曾龍盛': '/d-league/assets/players/陳公舘/曾龍盛.png',
  '洪品宇': '/d-league/assets/players/陳公舘/洪品宇.png',
  '陳品憲': '/d-league/assets/players/陳公舘/陳品憲.png',
  '林紀廷': '/d-league/assets/players/陳公舘/林紀廷.png',
  '張誌文': '/d-league/assets/players/陳公舘/張誌文.png',
  '吳明威': '/d-league/assets/players/陳公舘/吳明威.png',
  '洪彥翔': '/d-league/assets/players/陳公舘/洪彥翔.png',
  '王靖堯': '/d-league/assets/players/陳公舘/王靖堯.png',
  '李家勳': '/d-league/assets/players/陳公舘/李家勳.png',
  '陳俊介': '/d-league/assets/players/陳公舘/陳俊介.png',
  // ✅ 新增
  '蘇嘉雄': '/d-league/assets/players/陳公舘/蘇嘉雄.png',
  
  // L1 - 銅雀足球俱樂部
  '李相慶': '/d-league/assets/players/銅雀足球俱樂部/李相慶.png',
  '李偉豪': '/d-league/assets/players/銅雀足球俱樂部/李偉豪.png',
  '趙南聰': '/d-league/assets/players/銅雀足球俱樂部/趙南聰.png',
  '陳揚': '/d-league/assets/players/銅雀足球俱樂部/陳揚.png',
  '翁才竣': '/d-league/assets/players/銅雀足球俱樂部/翁才竣.png',
  '蘇智龍': '/d-league/assets/players/銅雀足球俱樂部/蘇智龍.png',
  '鄭孟育': '/d-league/assets/players/銅雀足球俱樂部/鄭孟育.png',
  '郭博彥': '/d-league/assets/players/銅雀足球俱樂部/郭博彥.png',
  '施博允': '/d-league/assets/players/銅雀足球俱樂部/施博允.png',
  '徐鈺凱': '/d-league/assets/players/銅雀足球俱樂部/徐鈺凱.png',
  '劉允閎': '/d-league/assets/players/銅雀足球俱樂部/劉允閎.png',
  '杜安': '/d-league/assets/players/銅雀足球俱樂部/杜安.png',
  '魏士閔': '/d-league/assets/players/銅雀足球俱樂部/魏士閔.png',
  '巫嘉德': '/d-league/assets/players/銅雀足球俱樂部/巫嘉德.png',
  '林宴丞': '/d-league/assets/players/銅雀足球俱樂部/林宴丞.png',
  '謝侑霖': '/d-league/assets/players/銅雀足球俱樂部/謝侑霖.png',
  '張斳恩': '/d-league/assets/players/銅雀足球俱樂部/張斳恩.png',
  '黃少威': '/d-league/assets/players/銅雀足球俱樂部/黃少威.png',
  '林晉威': '/d-league/assets/players/銅雀足球俱樂部/林晉威.png',
  '克魯茲': '/d-league/assets/players/銅雀足球俱樂部/克魯茲.png',
  // ✅ 新增
  '王奕中': '/d-league/assets/players/銅雀足球俱樂部/王奕中.png',
  
  // L1 - 酒號矯正署
  '林淮哲': '/d-league/assets/players/酒號矯正署/林淮哲.png',
  '何柏緯': '/d-league/assets/players/酒號矯正署/何柏緯.png',
  '李宗翰': '/d-league/assets/players/酒號矯正署/李宗翰.png',
  '黃有全': '/d-league/assets/players/酒號矯正署/黃有全.png',
  '顏廷邕': '/d-league/assets/players/酒號矯正署/顏廷邕.png',
  '陳吉龍': '/d-league/assets/players/酒號矯正署/陳吉龍.png',
  '謝孟軒': '/d-league/assets/players/酒號矯正署/謝孟軒.png',
  '曾健康': '/d-league/assets/players/酒號矯正署/曾健康.png',
  '許恩豪': '/d-league/assets/players/酒號矯正署/許恩豪.png',
  '李彼得': '/d-league/assets/players/酒號矯正署/李彼得.png',
  '林鈺閔': '/d-league/assets/players/酒號矯正署/林鈺閔.png',
  '林思維': '/d-league/assets/players/酒號矯正署/林思維.png',
  '林冠亨': '/d-league/assets/players/酒號矯正署/林冠亨.png',
  '鄭詠翰': '/d-league/assets/players/酒號矯正署/鄭詠翰.png',
  '陳揚青澔': '/d-league/assets/players/酒號矯正署/陳揚青澔.png',
  '吳啓明': '/d-league/assets/players/酒號矯正署/吳啓明.png',
  '施聖章': '/d-league/assets/players/酒號矯正署/施聖章.png',
  '劉庭嘉': '/d-league/assets/players/酒號矯正署/劉庭嘉.png',
  '何政緯': '/d-league/assets/players/酒號矯正署/何政緯.png',
  '洪毅瑋': '/d-league/assets/players/酒號矯正署/洪毅瑋.png',

  // L2 - 鹿逐俱樂部
  '陳麒竣': '/d-league/assets/players/鹿逐俱樂部/陳麒竣.png',
  '宋映德': '/d-league/assets/players/鹿逐俱樂部/宋映德.png',
  '謝詒婷': '/d-league/assets/players/鹿逐俱樂部/謝詒婷.png',
  '林伯仲': '/d-league/assets/players/鹿逐俱樂部/林伯仲.png',
  '李修沛': '/d-league/assets/players/鹿逐俱樂部/李修沛.png',
  '梶原航': '/d-league/assets/players/鹿逐俱樂部/梶原航.png',
  '鐘佳勳': '/d-league/assets/players/鹿逐俱樂部/鐘佳勳.png',
  '王子豪': '/d-league/assets/players/鹿逐俱樂部/王子豪.png',
  '陳泰盛': '/d-league/assets/players/鹿逐俱樂部/陳泰盛.png',
  '林敬祐': '/d-league/assets/players/鹿逐俱樂部/林敬祐.png',
  '陳穧元': '/d-league/assets/players/鹿逐俱樂部/陳穧元.png',
  '李祐任': '/d-league/assets/players/鹿逐俱樂部/李祐任.png',
  '蔡昀晏': '/d-league/assets/players/鹿逐俱樂部/蔡昀晏.png',
  '方韻雅': '/d-league/assets/players/鹿逐俱樂部/方韻雅.png',
  // ✅ 新增
  '林冠宇': '/d-league/assets/players/鹿逐俱樂部/林冠宇.png',
  '陳韋呈': '/d-league/assets/players/鹿逐俱樂部/陳韋呈.png',
  '林宜蓁': '/d-league/assets/players/鹿逐俱樂部/林宜蓁.png',

  // L2 - 屏東野猿足球俱樂部
  '邱文良': '/d-league/assets/players/屏東野猿足球俱樂部/邱文良.png',
  '周宗德': '/d-league/assets/players/屏東野猿足球俱樂部/周宗德.png',
  '尤尚佑': '/d-league/assets/players/屏東野猿足球俱樂部/尤尚佑.png',
  '林彥文': '/d-league/assets/players/屏東野猿足球俱樂部/林彥文.png',
  '林大雄': '/d-league/assets/players/屏東野猿足球俱樂部/林大雄.png',
  '林聿堂': '/d-league/assets/players/屏東野猿足球俱樂部/林聿堂.png',
  '張春生': '/d-league/assets/players/屏東野猿足球俱樂部/張春生.png',
  '周承政': '/d-league/assets/players/屏東野猿足球俱樂部/周承政.png',
  '簡法亦': '/d-league/assets/players/屏東野猿足球俱樂部/簡法亦.png',
  '謝晉元': '/d-league/assets/players/屏東野猿足球俱樂部/謝晉元.png',
  '陳奕盛': '/d-league/assets/players/屏東野猿足球俱樂部/陳奕盛.png',
  '鄧進成': '/d-league/assets/players/屏東野猿足球俱樂部/鄧進成.png',
  '黃旭盛': '/d-league/assets/players/屏東野猿足球俱樂部/黃旭盛.png',
  '張富勝': '/d-league/assets/players/屏東野猿足球俱樂部/張富勝.png',
  '簡罡正': '/d-league/assets/players/屏東野猿足球俱樂部/簡罡正.png',
  '吳明遠': '/d-league/assets/players/屏東野猿足球俱樂部/吳明遠.png',
  '連哲緯': '/d-league/assets/players/屏東野猿足球俱樂部/連哲緯.png',
  '林韋堯': '/d-league/assets/players/屏東野猿足球俱樂部/林韋堯.png',
  '李偲瑋': '/d-league/assets/players/屏東野猿足球俱樂部/李偲瑋.png',
  '蘇靖堂': '/d-league/assets/players/屏東野猿足球俱樂部/蘇靖堂.png',
  // ✅ 新增
  '黃浩程': '/d-league/assets/players/屏東野猿足球俱樂部/黃浩程.png',
  '吳明興': '/d-league/assets/players/屏東野猿足球俱樂部/吳明興.png',
  '蔡振偉': '/d-league/assets/players/屏東野猿足球俱樂部/蔡振偉.png',

  // L2 - 瘋Dog
  '黃震浩': '/d-league/assets/players/瘋Dog/黃震浩.png',
  '吳亦民': '/d-league/assets/players/瘋Dog/吳亦民.png',
  '林柏佑': '/d-league/assets/players/瘋Dog/林柏佑.png',
  '翁吉韡': '/d-league/assets/players/瘋Dog/翁吉韡.png',
  '王柏元': '/d-league/assets/players/瘋Dog/王柏元.png',
  '劉佳興': '/d-league/assets/players/瘋Dog/劉佳興.png',
  '文俊偉': '/d-league/assets/players/瘋Dog/文俊偉.png',
  '張博宇': '/d-league/assets/players/瘋Dog/張博宇.png',
  '徐鐸': '/d-league/assets/players/瘋Dog/徐鐸.png',
  '陳建宏': '/d-league/assets/players/瘋Dog/陳建宏.png',
  '趙學克': '/d-league/assets/players/瘋Dog/趙學克.png',
  '趙學邦': '/d-league/assets/players/瘋Dog/趙學邦.png',
  '江展宇': '/d-league/assets/players/瘋Dog/江展宇.png',
  '王亦瑋': '/d-league/assets/players/瘋Dog/王亦瑋.png',
  '戴威閎': '/d-league/assets/players/瘋Dog/戴威閎.png',
  '陳柏諧': '/d-league/assets/players/瘋Dog/陳柏諧.png',
  '蔡穎杰': '/d-league/assets/players/瘋Dog/蔡穎杰.png',
  // ✅ 新增
  '劉力瑋': '/d-league/assets/players/瘋Dog/劉力瑋.png',
  '吳詠祥': '/d-league/assets/players/瘋Dog/吳詠祥.png',

  // L2 - 鳥仕足球俱樂部
  '許御力': '/d-league/assets/players/鳥仕足球俱樂部/許御力.png',
  '王志誠': '/d-league/assets/players/鳥仕足球俱樂部/王志誠.png',
  '蔡軒誠': '/d-league/assets/players/鳥仕足球俱樂部/蔡軒誠.png',
  '于克元': '/d-league/assets/players/鳥仕足球俱樂部/于克元.png',
  '于克偉': '/d-league/assets/players/鳥仕足球俱樂部/于克偉.png',
  '蘇敦祺': '/d-league/assets/players/鳥仕足球俱樂部/蘇敦祺.png',
  '林欣楷': '/d-league/assets/players/鳥仕足球俱樂部/林欣楷.png',
  '邱睦容': '/d-league/assets/players/鳥仕足球俱樂部/邱睦容.png',
  '吳昱陞': '/d-league/assets/players/鳥仕足球俱樂部/吳昱陞.png',
  '鄭祖鏗': '/d-league/assets/players/鳥仕足球俱樂部/鄭祖鏗.png',
  '魏以恆': '/d-league/assets/players/鳥仕足球俱樂部/魏以恆.png',
  '李家諾': '/d-league/assets/players/鳥仕足球俱樂部/李家諾.png',
  '陳嫈文': '/d-league/assets/players/鳥仕足球俱樂部/陳嫈文.png',
  '陳光禪': '/d-league/assets/players/鳥仕足球俱樂部/陳光禪.png',
  '邱俊融': '/d-league/assets/players/鳥仕足球俱樂部/邱俊融.png',
  '莫嘉瑋': '/d-league/assets/players/鳥仕足球俱樂部/莫嘉瑋.png',
  '王竣弘': '/d-league/assets/players/鳥仕足球俱樂部/王竣弘.png',
  '林耀強': '/d-league/assets/players/鳥仕足球俱樂部/林耀強.png',
  '謝俊杰': '/d-league/assets/players/鳥仕足球俱樂部/謝俊杰.png',
  '劉偉洋': '/d-league/assets/players/鳥仕足球俱樂部/劉偉洋.png',
  // ✅ 新增
  '陳宇翔': '/d-league/assets/players/鳥仕足球俱樂部/陳宇翔.png',
  '陳學璋': '/d-league/assets/players/鳥仕足球俱樂部/陳學璋.png',
  '陳遠泰': '/d-league/assets/players/鳥仕足球俱樂部/陳遠泰.png',
  '高義莉': '/d-league/assets/players/鳥仕足球俱樂部/高義莉.png',
  '黃首駿': '/d-league/assets/players/鳥仕足球俱樂部/黃首駿.png',
  '劉康任': '/d-league/assets/players/鳥仕足球俱樂部/劉康任.png',

  // L2 - PPI TAINAN FC
  '杰菲': '/d-league/assets/players/PPI TAINAN FC/杰菲.png',
  '木哈馬': '/d-league/assets/players/PPI TAINAN FC/木哈馬.png',
  'Iradaf Mandaya G.A Bahrun': '/d-league/assets/players/PPI TAINAN FC/Iradaf Mandaya G.A Bahrun.png',
  '萬地': '/d-league/assets/players/PPI TAINAN FC/萬地.png',
  '伊拉曼': '/d-league/assets/players/PPI TAINAN FC/伊拉曼.png',
  '伊而凡': '/d-league/assets/players/PPI TAINAN FC/伊而凡.png',
  '麥羅': '/d-league/assets/players/PPI TAINAN FC/麥羅.png',
  '泰普曼': '/d-league/assets/players/PPI TAINAN FC/泰普曼.png',
  '拉非': '/d-league/assets/players/PPI TAINAN FC/拉非.png',
  '孺立': '/d-league/assets/players/PPI TAINAN FC/孺立.png',
  '布丹': '/d-league/assets/players/PPI TAINAN FC/布丹.png',
  '高世科': '/d-league/assets/players/PPI TAINAN FC/高世科.png',
  'YEHUDA GAGAH WICAKSONO': '/d-league/assets/players/PPI TAINAN FC/YEHUDA GAGAH WICAKSONO.png',
  '優沙': '/d-league/assets/players/PPI TAINAN FC/優沙.png',
  '拉拉': '/d-league/assets/players/PPI TAINAN FC/拉拉.png',
  '阿麥德': '/d-league/assets/players/PPI TAINAN FC/阿麥德.png',
  '牙提': '/d-league/assets/players/PPI TAINAN FC/牙提.png',
  '蘇凡迪': '/d-league/assets/players/PPI TAINAN FC/蘇凡迪.png',
  // ✅ 新增
  '劉駿輝': '/d-league/assets/players/PPI TAINAN FC/劉駿輝.png',
  
  // L2 - 蒼龍FC
  '盧冠宇': '/d-league/assets/players/蒼龍FC/盧冠宇.png',
  '沈家弘': '/d-league/assets/players/蒼龍FC/沈家弘.png',
  '王浩誠': '/d-league/assets/players/蒼龍FC/王浩誠.png',
  '毛邦澤': '/d-league/assets/players/蒼龍FC/毛邦澤.png',
  '葉晉嘉': '/d-league/assets/players/蒼龍FC/葉晉嘉.png',
  '張丞均': '/d-league/assets/players/蒼龍FC/張丞均.png',
  '林聖恩': '/d-league/assets/players/蒼龍FC/林聖恩.png',
  '潘星宇': '/d-league/assets/players/蒼龍FC/潘星宇.png',
  '楊承諺': '/d-league/assets/players/蒼龍FC/楊承諺.png',
  '洪子程': '/d-league/assets/players/蒼龍FC/洪子程.png',
  '潘晨維': '/d-league/assets/players/蒼龍FC/潘晨維.png',
  '郭彥廷': '/d-league/assets/players/蒼龍FC/郭彥廷.png',
  '鄧子博': '/d-league/assets/players/蒼龍FC/鄧子博.png',
  '丁誌暉': '/d-league/assets/players/蒼龍FC/丁誌暉.png',
  '林湧鈞': '/d-league/assets/players/蒼龍FC/林湧鈞.png',
  '黃歷迦': '/d-league/assets/players/蒼龍FC/黃歷迦.png',
  '吳嘉華': '/d-league/assets/players/蒼龍FC/吳嘉華.png',
  '林家鈞': '/d-league/assets/players/蒼龍FC/林家鈞.png',
  '曾少凱': '/d-league/assets/players/蒼龍FC/曾少凱.png',
  '蘇宗霆': '/d-league/assets/players/蒼龍FC/蘇宗霆.png',
  '吳志華': '/d-league/assets/players/蒼龍FC/吳志華.png',
  '李昆鴻': '/d-league/assets/players/蒼龍FC/李昆鴻.png',
  '郭愈': '/d-league/assets/players/蒼龍FC/郭愈.png',
};